config/routes.rb
Rails.application.routes.draw do

  resources :languages
  resources :submissions
  resources :countries
  resources :tags
  resources :pages
  resources :projects
  resources :series
  resources :organizations
  resources :trainlanguages
  resources :materialtypes
  #resources :searches
  resources :technicalareas
  resources :targetgroups
  resources :languages
  resources :target_groups
  resources :technical_areas
  resources :resources do
    collection do
      get :edit_multiple
      put :update_multiple
      #put :updatelogos
    end
  end
  resources :trainers
  resources :site_images
  resources :site_documents
  resources :post_documents
  devise_for :users
  resources :posts
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  get 'visitors/about', to: 'visitors#about', as: 'about'
  get 'visitors/faqs', to: 'visitors#faqs', as: 'faqs'
  get 'visitors/terms', to: 'visitors#terms', as: 'terms'
  #get 'visitors/results', to: 'visitors#results', as: 'results'

  get 'resources/newtranslation', to: 'resources#newtranslation', as: 'newtranslation'
  put 'updatelogos', to: 'resources#updatelogos', as: 'updatelogos'
  put 'updatelang', to: 'resources#updatelang', as: 'updatelang'
  put 'updatepostlogos', to: 'posts#updatepostlogos', as: 'updatepostlogos'
  get 'searchform', to: 'resources#search_resources', as: 'searchform'
  #get 'searches', to: 'searches#index', as: 'searches'
  get 'checkorgs', to: 'resources#checkorgs', as: 'checkorgs'
  get 'resources/check_proj', to: 'resources#check_proj', as: 'checkproj'
  root 'visitors#index'


  resources :users

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index

    self.fixseries

    @series = Series.where('(pid = 0 or pid is NULL) and language=1')
  end


   def fixseries

     resourcelinks = Oldlink.where('ctype = ?', "t")
     serieslinks = Oldlink.where('ctype = ?', "s")
     seriesDads = Oldlink.select("pnid,ptnid,plang,ptitle").group('pnid,ptnid,plang,ptitle')


     resourcelinks.each do |rl|
       parent= rl.pnid
       rnode = Resource.find_by_nid(rl.cnid)
       if !rnode.nil?
         rnode.pnid = rl.pnid
         rnode.save
       end

     end

     serieslinks.each do |sl|
       Series.create([{nid: sl.cnid, name: sl.ctitle, tnid: sl.ctnid, pnid: sl.pnid}])

     end


     seriesDads.each do |sd|
       Series.create([{nid: sd.pnid, name: sd.ptitle, tnid: sd.ptnid, language: sd.plang}])

     end


     @newseries= Series.where('pid is NULL and pnid > 0')
     @newseries.each do |n|
       getparent= Series.find_by_nid(n.pnid)
       n.pid = getparent.id
       n.save
     end




   end

  # GET /series/1
  # GET /series/1.json
  def show
    @subseries = Series.where('pid = ?', @series.id)
    @materials = Resource.where('series_id = ?', @series.id)


  end

  # GET /series/new
  def new
    @series = Series.new
    if !params[:id].nil?
      @engver=Series.find_by_id(params[:id])
    end




  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :body, :nid, :pnid, :language, :tnid, :tid, :pid)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<style>
    .pagetitle {
        color: orangered;
        font-size: 16px;
    }
    </style>

<div class="col-sm-7">
  <div class="panel panel-default">





    <div class="panel-body">

    <%= debug params %>






<%= form_for(@series) do |f| %>
          <%= hidden_field_tag :locale, I18n.locale %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


          <% if !params[:nid].nil? %>
              <% if params[:language] == '2' %>
                  <input type="hidden" name="language" value="2">
                  <input type="hidden" name="tnid" value="<%= params[:pnid] %>">
                         Arabic Content for Series:<br>
              <% end %>
              <% if params[:language] == '3' %>
                  <input type="hidden" name="language" value="2">
                  <input type="hidden" name="tnid" value="<%= params[:pnid] %>">
                  French Content for Series:<br>
              <% end %>

              <span class="pagetitle"><%= @engver.name %></span>
          <% end %>
          <hr>





  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :nid %><br>
    <%= f.number_field :nid %>
  </div>
  <div class="field">
    <%= f.label :pnid %><br>
    <%= f.number_field :pnid %>
  </div>

          <div class="field">
            <%= f.label 'Language' %><br>
            <%= f.select(:language, Language.to_a, :include_blank => true, :class => "form-control") %>
          </div>

  <div class="field">
    <%= f.label :tnid %><br>
    <%= f.number_field :tnid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

        </div>
      </div>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<script>
    $(document).ready(function() {
        $('#series').DataTable();
    } );
</script>

<style>
    .parent {
        color: orange;
        font-size: 10px;
    }

.toc {
    padding: 5px;
}

</style>



<p id="notice"><%= notice %></p>

<h1>Listing Series</h1>
<table class="toc" cellspacing="2" width="100%">

  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>

      <th># Sub</th>
      <th># Res</th>



      <th>pid</th>

      <th>tid</th>
      <th>Pnid</th>
      <th>Language</th>
      <th>Tnid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

    <tbody>
        <% @series.each do |s| %>
            <% subs=Series.where('pid = ?', s.id) %>
            <% resources=Resource.where('series_id = ?', s.id) %>

          <tr>
            <td><%= s.id %></td>
            <td><%= link_to s  do %><%= s.name %><%= s.pid %><% end %>

            <% if !s.pid.nil? and s.pid > 0 %>
            <% p = Series.find_by_id(s.pid) %>

            <% if !p.nil? %>

            <small class="color: orange">Series: <%= p.series.name %></small><br>

            <% end %>


            <% end %>



            </td>
            <td><%= subs.count %></td>
           <td><%= resources.count %></td>

            <td><%= s.pid %></td>
            <td><%= s.tid %></td>
            <td><%= s.pnid %></td>
            <td><%= s.language %></td>
            <td><%= s.tnid %></td>
            <td><%= link_to 'Show', s %></td>
            <td><%= link_to 'Edit', edit_series_path(s) %></td>
            <td><%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>

        <% end %>
    </tbody>
    </table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<style>
  .pagetitle {
      color: orangered;
      font-size: 16px;
  }


   .parent {
       color: orange;
       font-size: 10px;
   }



</style>


<p id="notice"><%= notice %></p>


<div class="col-sm-9">
<div class="panel panel-default">

  <div class="panel-body">
Series:<br>

    <span class="pagetitle"><%= @series.name %></span>

    <% if !@series.pid.nil? and @series.pid > 0 %>
        <% p = Series.find_by_id(@series.pid) %>

        <% if !p.nil? %>
            <br><span class="parent"> Belongs to: <%= p.name %></span>
        <% end %>


  <% end %>



    <div class="row">


      <%= link_to 'Edit', edit_series_path(:id=> @series.id, :language=> @series.language, :locale => I18n.locale), :class => "mb-sm btn btn-primary pull-right" %></li>


    </div>



<hr>
    <p>

  <%= @series.body %>
</p>


<p>
  <strong>Language:</strong>
  <%= @series.language_humanize %>
</p>

<p>
  <strong>Tnid:</strong>
  <%= @series.tnid %>
</p>


<h2>Series</h2>

 <% @subseries.each do |sub| %>
    <%= link_to sub do %><%= sub.name %><% end %><br>
<% end %>


<h2>Materials</h2>
<% @materials.each do |mat| %>
    <%= link_to mat do %><%= mat.title %><% end %><br>
<% end %>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>


  </div>

    </div>

  <div class="col-sm-5">
    <div class="panel panel-default">

      <div class="panel-body">

    <p>
    <strong>Nid:</strong>
    <%= @series.nid %>
    </p>

    <p>
      <strong>Pnid:</strong>
      <%= @series.pnid %>
    </p>
       <p>
          <strong>Tnid:</strong>
          <%= @series.tnid %>
        </p>


        <p>
          <strong>id:</strong>
          <%= @series.id %>
        </p>

        <p>
          <strong>Pid:</strong>
          <%= @series.pid %>
        </p>
        <p>
          <strong>Tid:</strong>
          <%= @series.tid %>
        </p>







<%#= link_to 'Arabic', series_index_path(@series.id), :class => "mb-sm btn btn-primary" %> |
<%#= link_to 'Arabic', series_index_path(@series.id), :class => "mb-sm btn btn-primary" %> |
</div>
      </div>
</div>