config/routes.rb
Rails.application.routes.draw do

  resources :languages
  resources :submissions
  resources :countries
  resources :tags
  resources :pages
  resources :projects
  resources :series
  resources :organizations
  resources :trainlanguages
  resources :materialtypes
  #resources :searches
  resources :technicalareas
  resources :targetgroups
  resources :languages
  resources :target_groups
  resources :technical_areas
  resources :resources do
    collection do
      get :edit_multiple
      put :update_multiple
      #put :updatelogos
    end
  end
  resources :trainers
  resources :site_images
  resources :site_documents
  resources :post_documents
  devise_for :users
  resources :posts
  resources :comments, :path_prefix => '/:commentable_type/:commentable_id'
  get 'visitors/about', to: 'visitors#about', as: 'about'
  get 'visitors/faqs', to: 'visitors#faqs', as: 'faqs'
  get 'visitors/terms', to: 'visitors#terms', as: 'terms'
  #get 'visitors/results', to: 'visitors#results', as: 'results'

  get 'resources/newtranslation', to: 'resources#newtranslation', as: 'newtranslation'
  put 'updatelogos', to: 'resources#updatelogos', as: 'updatelogos'
  put 'updatelang', to: 'resources#updatelang', as: 'updatelang'
  put 'updatepostlogos', to: 'posts#updatepostlogos', as: 'updatepostlogos'
  get 'searchform', to: 'resources#search_resources', as: 'searchform'
  #get 'searches', to: 'searches#index', as: 'searches'
  get 'checkorgs', to: 'resources#checkorgs', as: 'checkorgs'
  get 'resources/check_proj', to: 'resources#check_proj', as: 'checkproj'
  root 'visitors#index'


  resources :users

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base

  has_many :trainers_languages, :dependent => :destroy
  has_many :trainlanguages, :through => :trainers_languages

  has_many :trainers_countries, :dependent => :destroy
  has_many :countries, :through => :trainers_countries

  has_one :technicalarea,  :foreign_key => "specialty_id"

  has_many :specialties, :dependent => :destroy
  has_many :technicalareas, :through => :specialties

  extend EnumerateIt
  has_enumeration_for :gender
  has_enumeration_for :title


end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index

    @fixlangs = TrainersLanguage.where("trainer_id is NULL")
    @fixcntry = TrainersCountry.where("trainer_id is NULL")
    @fixspec = Specialty.where("trainer_id is NULL")

    @fixlangs.each do |fl|
      tnode= Trainer.find_by_nid(fl.nid)
      fl.trainer_id = tnode.id
      fl.save
    end

    @fixcntry.each do |fc|
      tnode= Trainer.find_by_nid(fc.nid)
      fc.trainer_id = tnode.id
      fc.save
    end
    
    @fixspec.each do |fs|
      tnode= Trainer.find_by_nid(fs.nid)
      fs.trainer_id = tnode.id
      fs.save
    end

    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
    @myotherspecialties = Specialty.where('trainer_id = ? ', @trainer.id)
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
  end

  # GET /trainers/1/edit
  def edit
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to @trainer, notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer }
      else
        format.html { render :edit }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    @trainer.destroy
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:title, :name_first, :name_last, :gender, :based_in, :city, :mepi_training, :mepi_trained, :phone, :email, :website, :experience, :specialty_id, :additional,
      :country, :nid, :specialty, :name_first_ar, :name_last_ar)
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/_form.html.erb
<div class="col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"> <%= @trainer.name_first %>  <%= @trainer.name_last %></h3>
    </div>
    <div class="panel-body">



    <%= form_for(@trainer) do |f| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

      <ul>
      <% @trainer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



          <div class="field">
            <%= f.label 'Salut' %><br>
            <%= f.select(:title, Title.to_a, :class => "form-control") %>
          </div>


  <div class="field">
    <%= f.label :name_first %><br>
    <%= f.text_field :name_first %>
  </div>
  <div class="field">
    <%= f.label :name_last %><br>
    <%= f.text_field :name_last %>
  </div>
          <div class="field">
            <%= f.label 'Gender' %><br>
            <%= f.select(:gender, Gender.to_a, :class => "form-control") %>
          </div>

  <div class="field">
    <%= f.label :based_in %><br>
    <%= f.collection_select(:based_in, Mepicountry.all, :id, :name, include_blank: true, :class => "form-control") %>

  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :mepi_training %><br>
    <%= f.check_box :mepi_training %>
  </div>
  <div class="field">
    <%= f.label :mepi_trained %><br>
    <%= f.check_box :mepi_trained %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_area :experience, :class => "form-control", :label => false, input_html: {rows: 10, cols: 50} %>

  </div>
  <div class="field">
    <%= f.label :specialty_id %><br>

    <%= f.collection_select(:specialty_id, Technicalarea.all, :id, :name, include_blank: true, :class => "form-control") %>
  </div>
  <div class="field">
    <%= f.label :additional %><br>
    <%= f.text_area :additional, :class => "form-control", :label => false, input_html: {rows: 10, cols: 50} %>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

    </div>
  </div>
</div>

app/views/trainers/_trainers_table.html.erb
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>


<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%= @tabletitle %></h4>
      </div>
      <div class="panel-body">
        <table id="example" class="hover" cellspacing="0" width="100%">
          <thead>
          <tr>
            <th>Name</th>

            <th>Gender</th>
            <th>Based in</th>



            <th>Email</th>

            <th>Specialty</th>

          </tr>
          </thead>
          <tbody>
          <% @trainers.each do |trainer| %>
              <tr>

                <td><%= link_to trainer do %> <%= trainer.name_first %> <%= trainer.name_last %><% end %></td>
                <td><%= trainer.gender_humanize %></td>
                <td><%= trainer.country %></td>


                <td><%= trainer.email %></td>

                <td><%= trainer.specialty %></td>



              </tr>
          <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- END DATATABLE 1 -->

app/views/trainers/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trainers</h1>




<%= render partial: 'trainers/trainers_table' %>


<br>

<%= link_to 'New Trainer', new_trainer_path %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-6">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= @trainer.name_first %>  <%= @trainer.name_last %></h3>
  </div>
  <div class="panel-body">






<p>
  <strong>Gender:</strong>
  <%= @trainer.gender_humanize %>
</p>

<p>
  <strong>Based in:</strong>
  <%= @trainer.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @trainer.city %>
</p>

<p>
  <strong>Mepi training:</strong>
  <%= @trainer.mepi_training %>
</p>

<p>
  <strong>Mepi trained:</strong>
  <%= @trainer.mepi_trained %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @trainer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trainer.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @trainer.website %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @trainer.experience %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @trainer.specialty %>
</p>


    <strong>Secondary Technical Areas:</strong>
    <% @myotherspecialties.each do |area| %>
        <% thisspec = Technicalarea.find(area.technicalarea_id) %>
        <%= thisspec.name %>
        &nbsp;|&nbsp;
    <% end %><br>


    <p>
  <strong>Additional:</strong>
  <%= @trainer.additional %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>
<%= link_to 'Destroy', @trainer, method: :delete, data: { confirm: 'Are you sure?' } %>


  </div>
</div>
</div>